name: Pull Request check

on:
  pull_request:

jobs:
  On-pull-request:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: ['4.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get tags
        run: git fetch --tags origin

      - name: Getting latest version & check if version is available
        run: |
          target_branch="${{ github.base_ref }}"
          if [ "$target_branch" != "main" ]; then
            echo "Verificação de versão ignorada pois a branch de destino é '$target_branch'"
            exit 0
          fi
          VERSION=$(cat ./RELEASE_NOTES.json | jq -r .latest_version)
          echo "$VERSION" | grep -G -q "^[0-9]*\.[0-9]*\.[0-9]*$"
          if [ $? -ne 0 ]; then
            echo "Versão fora do formato ou não encontrada"
            exit 1
          fi
          GIT_TAG=$(git tag -l "$VERSION")
          if [ "$GIT_TAG" != "" ]; then
            echo "Versão já existe. Bump de versão necessário"
            exit 1
          fi
          # Check if all keys exists
          cat ./RELEASE_NOTES.json | jq -r '."'$VERSION'".custom_firmware_compatibilities | any'
          cat ./RELEASE_NOTES.json | jq -r '."'$VERSION'".tr069_compatibilities | any'
          cat ./RELEASE_NOTES.json | jq -r '."'$VERSION'".fixes | any'
          cat ./RELEASE_NOTES.json | jq -r '."'$VERSION'".improvements | any'
          cat ./RELEASE_NOTES.json | jq -r '."'$VERSION'".features | any'

          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      #- name: NPM Run build
      #  run: npm run build

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-db: flashman
      
      #- name: Run unit tests
      #  run: npm run test
      
      - name: Initializing flashman
        run: |
          set -a
          . ./test.env
          set +a
          echo Running node version: "$(node --version)"
          node ./bin/www &

      - name: Run Blackbox tests
        run: npm run bb-test
      
      - name: Killing flashman process
        if: always()
        run: kill $(pgrep node)
