name: Pull Request check

on:
  pull_request:
    branches: [ development ]

jobs:
  On-pull-to-development:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: ['4.4']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tags
        run: git fetch --tags origin

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: rs0
          mongodb-db: flashman
      
      - name: Setting up genieacs
        run: |
          set -a ; . ./test.env ; set +a
          cd ..
          git clone https://github.com/anlix-io/genieacs.git
          cd genieacs
          npm install
          npm run build
          node ./dist/bin/genieacs-nbi &
          sleep 3
          node ./dist/bin/genieacs-cwmp &

      - name: Initializing flashman
        run: |
          set -a
          . ./test.env
          set +a
          echo Running node version: "$(node --version)"
          node ./bin/www &
          sleep 15

      - name: Run Blackbox tests
        run: npm run bb-test

      - name: Destroying mongodb container
        if: ${{ always() }}
        run: docker container kill mongodb ; docker container prune -f
      
      - name: Removing current genieacs folder
        if: ${{ always() }}
        run: |
          rm -r ../genieacs/ ;
