name: Master pull request checks

on:
  pull_request:
    branches: [ master, feature/ci-merge-to ]

jobs:
  On-pull-to-master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Getting latest version & check if version is available
        run: |
          VERSION=$(cat ./RELEASE_NOTES.json | jq -r .latest_version)
          echo "$VERSION" | grep -G -q "^[0-9]*\.[0-9]*\.[0-9]*$"
          echo "Teste se versão está no formato"
          if [ $? -ne 0 ]; then
            echo "Versão fora do formato ou não encontrada"
            exit 1
          fi
          echo "Teste se versão já existe"
          if [ $(git tag -l "$VERSION") ]; then
            echo "Versão já existe. Bump de versão necessário"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & run tests
        run: |
          npm install
          npm test
