name: Pull Request check

on:
  pull_request:
    branches: [ development ]

jobs:
  On-pull-to-development:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get tags
        run: git fetch --tags origin

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test
